### PR TITLE
Action ensure_line_is_present includes spaces

### PR DESCRIPTION
**Pull request by lzap**
This action was previously "seding" the line into this form:

    right_side=left_side

I refactored this using native Ruby regexp and to include a spaces around, so
TFTP service does start fine (it requires spaces around).

### CODE REVIEW

**Comment by dLobatog** [comment]
@lzap I've tested it and it produces the right output - the README is a big plus 👍 (I don't have merge access here)

**Comment by lzap** [comment]
Oh I can't give you merge access, could you please @domcleal ? I am planning new release today.

**Comment by dLobatog** [comment]
@lzap I'm definitely no expert on this plugin (just a occasional user), in these cases I think it's fine if you merge your own PRs. Though I can help you with double checking them if you want, like in this case.

**Comment by lzap** [comment]
@domcleal if you could enable also rebase and merge for this repo, thanks!

**Comment by domcleal** [comment]
I enabled all merge options, you can maintain the @theforeman/hammer-admin team yourself.

**Pull request merged**
