### PR TITLE
Fixes #32954 - Remove pulp2 service definition

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thank you, let's get this in.

**Comment by lzap** [comment]
Can you rebase? I made an attept via github but it does not work :(

**Comment by wbclark** [comment]
> Can you rebase? I made an attept via github but it does not work :(

Thanks for the reviews, Lzap, I will rebase.

P.S. Does it make sense to do one versioned release before merging this, with the addition of redis + pulpcore, prior to removal yet of pulp2? In particular, this would be useful for troubleshooting pulp 2to3 migration where both versions are running.

**Comment by lzap** [comment]
> P.S. Does it make sense to do one versioned release before merging this, with the addition of redis + pulpcore, prior to removal yet of pulp2? In particular, this would be useful for troubleshooting pulp 2to3 migration where both versions are running.

If you think this is gonna be useful, then absolutely. I will then push a gem to rubygems and we can proceed with releasing a new version too.

**Comment by lzap** [comment]
Successfully registered gem: hammer_cli_foreman_admin (1.0.0)

**Comment by lzap** [comment]
And pushed 1.1 as well with this patch:

https://github.com/theforeman/foreman-packaging/pull/6896

**Comment by lzap** [comment]
Thanks!

**Comment by wbclark** [comment]
TYVM!

**Pull request merged**
