### PR TITLE
Fixes #32597 - add support for puppet5+

### PR DESCRIPTION
**Pull request by lzap**
SSIA

To test just update the yaml command on an instance and try it.

Disclaimer: I haven't tried it myself :-)

### CODE REVIEW

**Comment by lzap** [comment]
@ofedoren thanks! I will do a gem release and packaging then. Please test or I can spin an instance too.

**Review by ofedoren — APPROVED** [review]
Seems to be working, the value is being set as per documentation:
ScreenShot-1621080535200

Although it breaks indentation a bit. And if permissions for `logback.xml` are different from the ones which are used to run hammer then it just skips the component silently.

ACK by me for now, I'll not merge yet in case you want to change something :) Otherwise just ping me and I'll merge.

**Comment by ehelms** [comment]
You may want to create a follow up issue and align to the tracker as we are dropping Puppet 5 support -- https://projects.theforeman.org/issues/32609

**Comment by lzap** [comment]
Thanks merging.

Done: https://projects.theforeman.org/issues/32697

We don't need to rush with this one, the tool skips non-existing files silently so it will continue working just fine.

**Pull request merged**
